cluster:
  name: minikube-localhost

destinations:
  - name: logsService
    type: loki
    url: http://loki-grafana-cloud-endpoint/loki/api/v1/push
    auth:
      type: basic
      usernameKey: lokiUsername
      passwordKey: agentToken
    secret:
      create: false
      name: k8s-monitoring
      namespace: observability

alloy-logs:
  enabled: false

  logging:
    level: warn
    format: logfmt

  configReloader:
    enabled: false

  controller:
    podAnnotations: { kubernetes.azure.com/set-kube-service-host-fqdn: "true" }
    volumes:
      extra:
        - name: alloy-log-positions
          hostPath:
            path: /var/alloy-log-storage
            type: DirectoryOrCreate
    tolerations:
      - operator: Exists

  alloy:
    storagePath: /var/lib/alloy
    mounts:
      extra:
        - name: alloy-log-positions
          mountPath: /var/lib/alloy
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "1000m"
    extraEnv:
      - name: PLATFORM
        value: minikube
